[2023-07-27T07:06:34.947+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-03-05T00:00:00+00:00 [queued]>
[2023-07-27T07:06:34.996+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-03-05T00:00:00+00:00 [queued]>
[2023-07-27T07:06:34.997+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T07:06:35.040+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-27T07:06:35.043+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T07:06:35.390+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_records_from_overall_data> on 2022-03-05 00:00:00+00:00
[2023-07-27T07:06:35.458+0000] {standard_task_runner.py:55} INFO - Started process 1441 to run task
[2023-07-27T07:06:35.481+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineer_jobs_dag', 'extract_relevant_records_from_overall_data', 'scheduled__2022-03-05T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmp75sdmz7_']
[2023-07-27T07:06:35.490+0000] {standard_task_runner.py:83} INFO - Job 258: Subtask extract_relevant_records_from_overall_data
[2023-07-27T07:06:36.455+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-03-05T00:00:00+00:00 [running]> on host bc3380e7707e
[2023-07-27T07:06:37.334+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=your-email@example.com
AIRFLOW_CTX_DAG_OWNER=ebejale
AIRFLOW_CTX_DAG_ID=data_engineer_jobs_dag
AIRFLOW_CTX_TASK_ID=extract_relevant_records_from_overall_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-05T00:00:00+00:00
[2023-07-27T07:06:37.406+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 63, in extract_relevant_records_from_overall_data
    for i in range(len(data['data'])):
KeyError: 'data'
[2023-07-27T07:06:37.497+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_engineer_jobs_dag, task_id=extract_relevant_records_from_overall_data, execution_date=20220305T000000, start_date=20230727T070634, end_date=20230727T070637
[2023-07-27T07:06:37.974+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 258 for task extract_relevant_records_from_overall_data ('data'; 1441)
[2023-07-27T07:06:38.140+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-27T07:06:38.522+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
