[2023-07-27T07:36:04.364+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2023-07-27T07:36:04.676+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2023-07-27T07:36:04.708+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T07:36:04.740+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-07-27T07:36:04.772+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T07:36:05.221+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_records_from_overall_data> on 2022-05-12 00:00:00+00:00
[2023-07-27T07:36:05.383+0000] {standard_task_runner.py:55} INFO - Started process 3094 to run task
[2023-07-27T07:36:05.451+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineer_jobs_dag', 'extract_relevant_records_from_overall_data', 'scheduled__2022-05-12T00:00:00+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmp2wvzpy6i']
[2023-07-27T07:36:05.485+0000] {standard_task_runner.py:83} INFO - Job 475: Subtask extract_relevant_records_from_overall_data
[2023-07-27T07:36:06.381+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2022-05-12T00:00:00+00:00 [running]> on host bc3380e7707e
[2023-07-27T07:36:08.088+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=your-email@example.com
AIRFLOW_CTX_DAG_OWNER=ebejale
AIRFLOW_CTX_DAG_ID=data_engineer_jobs_dag
AIRFLOW_CTX_TASK_ID=extract_relevant_records_from_overall_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T00:00:00+00:00
[2023-07-27T07:36:08.409+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 63, in extract_relevant_records_from_overall_data
    for i in range(len(data['data'])):
KeyError: 'data'
[2023-07-27T07:36:08.630+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_engineer_jobs_dag, task_id=extract_relevant_records_from_overall_data, execution_date=20220512T000000, start_date=20230727T073604, end_date=20230727T073608
[2023-07-27T07:36:09.085+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 475 for task extract_relevant_records_from_overall_data ('data'; 3094)
[2023-07-27T07:36:09.180+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-27T07:36:09.871+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
