[2023-07-27T09:02:30.462+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-27T09:02:30.704+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-07-27T09:02:30.706+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T09:02:30.922+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-07-27T09:02:30.924+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-27T09:02:31.541+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_records_from_overall_data> on 2023-01-01 00:00:00+00:00
[2023-07-27T09:02:31.592+0000] {standard_task_runner.py:55} INFO - Started process 8284 to run task
[2023-07-27T09:02:31.633+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_engineer_jobs_dag', 'extract_relevant_records_from_overall_data', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '1144', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpi2pl0xw4']
[2023-07-27T09:02:31.726+0000] {standard_task_runner.py:83} INFO - Job 1144: Subtask extract_relevant_records_from_overall_data
[2023-07-27T09:02:33.043+0000] {task_command.py:389} INFO - Running <TaskInstance: data_engineer_jobs_dag.extract_relevant_records_from_overall_data scheduled__2023-01-01T00:00:00+00:00 [running]> on host bc3380e7707e
[2023-07-27T09:02:35.612+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=kasimir.Ikuenobe@hotmail.com
AIRFLOW_CTX_DAG_OWNER=ebejale
AIRFLOW_CTX_DAG_ID=data_engineer_jobs_dag
AIRFLOW_CTX_TASK_ID=extract_relevant_records_from_overall_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-07-27T09:02:35.911+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 81, in extract_relevant_records_from_overall_data
    for i in range(len(data['data'])):
KeyError: 'data'
[2023-07-27T09:02:36.252+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_engineer_jobs_dag, task_id=extract_relevant_records_from_overall_data, execution_date=20230101T000000, start_date=20230727T090230, end_date=20230727T090236
[2023-07-27T09:02:37.997+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1144 for task extract_relevant_records_from_overall_data ('data'; 8284)
[2023-07-27T09:02:38.226+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-27T09:02:38.983+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
